name: pyvisor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.3.1
  - numpy=1.24.4
  - pandas=1.5.3
  - scipy=1.10.1
  - pillow=9.5.0
  - matplotlib=3.7.1
  - pims=0.6.1
  - tqdm=4.66.1
  - pip:
      - pygame==2.1.3
      - av==10.0.0
      - moviepy==1.0.3
      - dill==0.3.7
      - xlsxwriter==3.1.2
      - PyQt5==5.15.10
      - opencv-python==4.8.1.78
